### ISSUE TITLE
最終フレームが変更できないプロジェクトで固まる

### ISSUE THREAD

**Issue by nanypoco** [hebiiro/AviUtl-Plugin-AdjustLastFrame#1]
Aviutl本体に動画をD&Dした時などで「最後のオブジェクト位置を～」が有効でない(グレーアウト)場合に、このプラグインが動作するとAviutlの操作が不能になります

コマンドを送信しても実際には位置が変動しない為に、無限ループが起こっている様に見えます
Aviutl1.10、拡張編集0.92とこのプラグインのみの環境で再現しました

**Comment by hebiiro** [comment]
私の環境では再現できませんでした。
一応 2.0.0 をリリースしたので試してみてください。

**Comment by hebiiro** [comment]
ドラッグアンドドロップしたときではなくて、その後タイムラインにアイテムを配置したときにフリーズするんですね。それならバージョン 2.0.1 で対応できたと思います。

**Comment by nanypoco** [comment]
対応ありがとうございます。
